Map<String, List<String>> subtopics = {
  "Music": [
    "Pop",
    "Rock",
    "Hip hop",
    "Country",
    "Jazz",
    "Classical",
    "Electronic",
    "Folk",
    "Soul",
    "R&B",
    "Blues",
    "Reggae",
    "Latin",
    "World",
    "Metal",
    "Punk",
    "Alternative",
    "Indie",
    "Funk",
    "Gospel",
    "Techno",
    "House",
    "Trance",
    "Dubstep",
    "Drum and bass",
    "Ambient",
    "Chillout",
    "New age",
    "Industrial",
    "Noise",
    "Experimental",
    "Avant-garde",
    "Singer-songwriter",
    "Acoustic",
    "Bluegrass",
    "Celtic",
    "Flamenco",
    "Tango",
    "Salsa",
    "Bhangra",
    "K-pop",
    "J-pop",
    "C-pop",
    "Vocaloid",
    "Musicals",
    "Opera",
    "Operetta",
    "Oratorio"
  ],
  "Entertainment": [
    "Movies",
    "Television",
    "Streaming",
    "Awards shows",
    "Celebrities",
    "Gossip",
    "Reality TV",
    "Talk shows",
    "Game shows",
    "Variety shows",
    "Comedy",
    "Drama",
    "Action",
    "Adventure",
    "Sci-fi",
    "Fantasy",
    "Thriller",
    "Horror",
    "Mystery",
    "Romance",
    "Crime",
    "War",
    "Historical",
    "Biographical",
    "Documentary",
    "Animation",
    "Live-action",
    "Adaptations",
    "Remakes",
    "Sequel",
    "Prequel",
    "Spin-off",
    "Parody",
    "Musical",
    "Experimental",
    "Independent",
    "Art house",
    "Foreign",
    "Cult",
    "Classic",
    "Blockbuster",
    "Box office",
    "Oscars",
    "Emmys",
    "Grammys",
    "Tonys",
    "Golden Globes"
  ],
  "Sports": [
    "Football",
    "Soccer",
    "Basketball",
    "Baseball",
    "Hockey",
    "Tennis",
    "Golf",
    "Cricket",
    "Rugby",
    "American football",
    "Athletics",
    "Boxing",
    "MMA",
    "Wrestling",
    "Weightlifting",
    "Powerlifting",
    "Bodybuilding",
    "Martial"
  ],
  "Gaming": [
    "PC gaming",
    "Console gaming",
    "mobile gaming",
    "VR gaming",
    "AR gaming",
    "eSports",
    "MMOs",
    "RPGs",
    "Shooters",
    "Action",
    "Adventure",
    "Strategy",
    "Simulation",
    "Sports",
    "Racing",
    "Fighting",
    "Music",
    "Puzzle",
    "Platformer",
    "Open world",
    "First-person",
    "Third-person",
    "Side-scroller",
    "Top-down",
    "Point-and-click",
    "Text-based",
    "Visual novel",
    "Life sim",
    "City-building",
    "Sandbox",
    "Survival",
    "Horror",
    "Fantasy",
    "Sci-fi",
    "Historical",
    "Medieval",
    "Steampunk",
    "Cyberpunk",
    "Post-apocalyptic",
    "Anime",
    "Manga",
    "DC Comics",
    "Marvel Comics",
    "Disney",
    "Pixar",
    "Nickelodeon",
    "Cartoon Network",
    "Dreamworks",
    "Nintendo",
    "Playstation",
    "Xbox",
    "Sega"
  ],
  "Fashion & Beauty": [
    "Makeup",
    "Skincare",
    "Hair",
    "Nails",
    "Fragrance",
    "Beauty products",
    "Beauty tools",
    "Beauty trends",
    "Beauty tips",
    "Beauty routines",
    "Beauty hacks",
    "Beauty tutorials",
    "Beauty vlogs",
    "Beauty influencers",
    "Beauty blogs",
    "Beauty magazines",
    "Beauty stores",
    "Beauty salons",
    "Beauty spas",
    "Fashion",
    "Style",
    "Clothing",
    "Accessories",
    "Shoes",
    "Bags",
    "Jewelry",
    "Watches",
    "Eyewear",
    "Hats",
    "Scarves",
    "Gloves",
    "Belts",
    "Socks",
    "Tights",
    "Underwear",
    "Lingerie",
    "Sleepwear",
    "Swimwear",
    "Sportswear",
    "Outerwear",
    "Suits",
    "Dresses",
    "Skirts",
    "Pants",
    "Jeans",
    "Shorts",
    "Leggings",
    "Tops",
    "T-shirts",
    "Sweaters",
    "Cardigans",
    "Hoodies",
    "Jackets",
    "Coats",
    "Fashion trends",
    "Fashion tips",
    "Fashion routines",
    "Fashion hacks",
    "Fashion tutorials",
    "Fashion vlogs",
  ],
  "Fashion & Food": [
    "Food",
    "Cooking",
    "Baking",
    "Recipes",
    "Ingredients",
    "Grocery shopping",
    "Meal planning",
    "Meal prep",
    "Food blogs",
    "Food magazines",
    "Food shows",
    "Food channels",
    "Food influencers",
    "Food vlogs",
    "Food tutorials",
    "Food hacks",
    "Food trends",
    "Food tips",
    "Food routines",
    "Food history",
    "Food culture",
    "Food science",
    "Food nutrition",
    "Food allergies",
    "Food sensitivities",
    "Food intolerance",
    "Food safety",
    "Food sanitation",
    "Food handling",
    "Food storage",
    "Food presentation",
    "Food aesthetics",
    "Food photography",
    "Food art",
    "Food design",
    "Food innovation",
    "Food sustainability",
    "Food waste",
    "Food security",
    "Food justice",
    "Food politics",
    "Food policy",
    "Food economics",
    "Food marketing",
    "Food branding",
    "Food advertising",
    "Food PR",
    "Food social media",
    "Food SEO",
    "Food SEO",
    "Food content marketing",
    "Food branding",
    "Food advertising",
    "Food PR",
    "Food social media",
    "Food SEO",
    "Food content marketing",
  ],
  "Business and Finance": [
    "Entrepreneurship",
    "Startups",
    "Small business",
    "Freelancing",
    "Consulting",
    "Coaching",
    "Mentoring",
    "Advisory",
    "Professional services",
    "Online business",
    "eCommerce",
    "Dropshipping",
    "Affiliate marketing",
    "Blogging",
    "Vlogging",
    "Podcasting",
    "Content marketing",
    "Social media marketing",
    "SEO",
    "Email marketing",
    "Influencer marketing",
    "Marketing strategy",
    "Marketing plan",
    "Marketing budget",
    "Marketing tactics",
    "Marketing channels",
    "Marketing metrics",
    "Marketing analysis",
    "Marketing trends",
    "Marketing research",
    "Marketing psychology",
    "Marketing communications",
    "Marketing branding",
    "Marketing advertising",
    "Marketing PR",
    "Marketing social media",
    "Marketing SEO",
    "Marketing content marketing",
    "Financial management",
    "Financial planning",
    "Financial analysis",
    "Financial modeling",
    "Financial projections",
    "Financial ratios",
    "Financial statements",
    "Financial reporting",
    "Financial auditing",
    "Financial compliance",
    "Financial regulation",
    "Financial risk management",
    "Financial insurance",
    "Financial investments",
    "Financial markets",
    "Financial trading",
    "Financial derivatives",
  ],
  "Arts & Culture": [
    "Art",
    "Painting",
    "Drawing",
    "Sculpture",
    "Printmaking",
    "Photography",
    "Digital art",
    "Graphic design",
    "Illustration",
    "Animation",
    "Comics",
    "Manga",
    "Graphic novels",
    "Webcomics",
    "Art history",
    "Art theory",
    "Art criticism",
    "Art movements",
    "Art styles",
    "Art techniques",
    "Art media",
    "Art materials",
    "Art processes",
    "Art skills",
    "Art forms",
    "Art genres",
    "Art subjects",
    "Art themes",
    "Art symbolism",
    "Art storytelling",
    "Art representation",
    "Art narrative",
    "Art motifs",
    "Art iconography",
    "Art archetypes",
    "Art mythology",
    "Art folklore",
    "Art religion",
    "Art spirituality",
    "Art philosophy",
    "Art psychology",
    "Art sociology",
    "Art anthropology",
    "Art politics",
    "Art economics",
    "Art law",
    "Art ethics",
    "Art activism",
    "Art social justice",
    "Art education",
    "Art pedagogy",
    "Art curricula",
    "Art assessment",
    "Art teaching methods",
    "Art learning theories",
    "Art classroom management",
    "Art professional development",
    "Art teacher training",
    "Art teacher certification",
    "Art teacher resources",
    "Art teacher support",
    "Art teacher networking",
    "Art teacher advocacy",
    "Art teacher unions",
    "Art teacher associations",
    "Art teacher conferences",
    "Art teacher workshops",
    "Art teacher seminars",
    "Art teacher webinars",
    "Art teacher online courses",
    "Art teacher MOOCs",
    "Art teacher podcasts",
    "Art teacher blogs",
    "Art teacher vlogs",
    "Art teacher social media",
    "Art teacher forums",
    "Art teacher communities",
    "Art teacher groups",
    "Art teacher networks",
  ],
  "Technology": [
    "Computer science",
    "Programming",
    "Software development",
    "Web development",
    "Mobile development",
    "Game development",
    "Data science",
    "Artificial intelligence",
    "Machine learning",
    "Deep learning",
    "Natural language processing",
    "Computer vision",
    "Robotics",
    "Internet of things",
    "Cybersecurity",
    "Cryptography",
    "Network security",
    "Information security",
    "Application security",
    "Operating systems",
    "Windows",
    "MacOS",
    "Linux",
    "Unix",
    "Databases",
    "SQL",
    "NoSQL",
    "Big data",
    "Data management",
    "Data analysis",
    "Data visualization",
    "Data mining",
    "Data modeling",
    "Data",
  ],
  "Travel": [
    "Tourism",
    "Hospitality",
    "Leisure",
    "Vacation",
    "Holiday",
    "Adventure",
    "Sightseeing",
    "Exploration",
    "Cultural exchange",
    "Education",
    "Relaxation",
    "Wellness",
    "Health",
    "Fitness",
    "Nature",
    "Outdoors",
    "Wildlife",
    "Ecotourism",
    "Agritourism",
    "Heritage",
    "History",
    "Archeology",
    "Geography",
    "Geology",
    "Climate",
    "Weather",
    "Seasons",
    "Scenery",
    "Landscapes",
    "Mountains",
    "Forests",
    "Deserts",
    "Beaches",
    "Islands",
    "Lakes",
    "Rivers",
    "Oceans",
    "Seas",
    "Waterfalls",
    "Caves",
    "National parks",
    "Protected areas",
    "Conservation",
    "Preservation",
    "Sustainable development",
    "Environmental protection",
    "Climate change",
    "Green energy",
    "Green transportation",
    "Green tourism",
    "Carbon offsetting",
    "Transportation",
    "Air travel",
    "Airline industry",
    "Airports",
    "Airlines",
    "Airplanes",
    "Aviation",
    "Flight",
    "Pilot",
    "Cockpit",
    "Crew",
    "Passenger",
    "Baggage",
    "Security",
    "Safety",
    "Air traffic control",
    "Aeronautics",
    "Aerodynamics",
    "Aeronautical engineering",
    "Aerospace engineering",
    "Rail travel",
    "Railway industry",
    "Trains",
    "Railroads",
    "Railway stations",
    "Railway tracks",
    "Railway infrastructure",
    "Railway maintenance",
    "Railway safety",
    "Railway security",
    "Railway engineering",
    "Railway logistics",
    "Railway operations",
    "Railway management",
    "Railway economics",
    "Railway policy",
    "Railway regulation",
    "Railway advocacy",
    "Railway unions",
    "Railway associations",
    "Railway conferences",
    "Railway workshops",
    "Railway seminars",
    "Railway webinars",
    "Railway online courses",
    "Railway MOOCs",
    "Railway podcasts",
    "Railway blogs",
    "Railway vlogs",
    "Railway social media",
    "Railway forums",
    "Railway communities",
    "Railway groups",
    "Railway networks",
    "Road travel",
    "Road transportation",
    "Road infrastructure",
    "Road maintenance",
    "Road safety",
    "Road security",
    "Road engineering",
  ],
  "Outdoors": [
    "Hiking",
    "Backpacking",
    "Camping",
    "Fishing",
    "Hunting",
    "Boating",
    "Canoeing",
    "Kayaking",
    "Rafting",
    "Sailing",
    "Surfing",
    "Swimming",
    "Diving",
    "Snorkeling",
    "Scuba diving",
    "Rock climbing",
    "Mountaineering",
    "Bouldering",
    "Canyoneering",
    "Rappelling",
    "Ziplining",
    "Skydiving",
    "Paragliding",
    "Hang gliding",
    "Hot air ballooning",
    "Ultralight aircraft",
    "Glider",
    "Parachuting",
    "Base jumping",
    "Wingsuit flying",
    "Bungee jumping",
    "Skiing",
    "Snowboarding",
    "Ice skating",
    "Ice climbing",
    "Snowshoeing",
    "Cross-country skiing",
    "Downhill skiing",
    "Freestyle skiing",
    "Alpine skiing",
    "Nordic skiing",
    "Telemark skiing",
    "Snowboarding",
    "Freeride snowboarding",
    "Freestyle snowboarding",
    "Alpine snowboarding",
    "Nordic snowboarding",
    "Snowboard cross",
    "Snowboard halfpipe",
    "Snowboard slopestyle",
    "Snowboard big air",
    "Snowboardparks",
    "Snowboard backcountry",
    "Snowboard powder",
    "Snowboard jumps",
    "Snowboard rails",
    "Snowboard boxes",
    "Snowboard pipes",
    "Snowboard halfpipes",
    "Snowboard slopestyles",
    "Snowboard big airs",
    "Snowboard resorts",
    "Snowboard lodges",
    "Snowboard rentals",
    "Snowboard lessons",
    "Snowboard guides",
    "Snowboard tours",
    "Snowboard competitions",
    "Snowboard events",
    "Snowboard festivals",
    "Snowboard expos",
    "Snowboard trade shows",
    "Snowboard conferences",
    "Snowboard workshops",
    "Snowboard seminars",
    "Snowboard webinars",
    "Snowboard online courses",
    "Snowboard MOOCs",
    "Snowboard podcasts",
    "Snowboard blogs",
    "Snowboard vlogs",
    "Snowboard social media",
    "Snowboard forums",
    "Snowboard communities",
    "Snowboard groups",
    "Snowboard networks",
    "Bicycling",
    "Mountain biking",
    "Road biking",
    "Cycling",
    "BMX",
    "Track cycling",
    "Cyclocross",
    "Gravel cycling",
    "Touring cycling",
    "Commuting cycling",
    "Utilitarian cycling",
    "Recreational cycling",
    "Sports cycling",
    "Competitive cycling",
    "Cycling training",
    "Cycling coaching",
  ],
  "Animation & comics": [
    "2D animation",
    "3D animation",
    "Stop-motion animation",
    "Hand-drawn animation",
    "Computer-generated animation",
    "Anime",
    "Manga",
    "Comic strips",
    "Graphic novels",
    "Webcomics",
    "Superhero comics",
    "Independent comics",
    "Political cartoons",
    "Animation studios",
    "Animation techniques",
    "Character design",
    "Storyboarding",
    "Scriptwriting for animation",
    "Voice acting in animation",
    "Music in animation",
    "Sound design in animation",
    "Animation history",
    "Animation theory",
    "Animation software",
    "Animation careers",
    "Animation festivals",
    "Animation awards",
    "Animation and technology",
    "Animation and culture",
    "Animation and social issues",
    "Animation and education",
    "Animation and psychology",
    "Animation and philosophy",
    "Animation and politics",
    "Animation and art",
    "Animation and literature",
    "Animation and music",
    "Animation and film",
    "Animation and television",
    "Animation and gaming",
    "Animation and advertising",
    "Animation and branding",
    "Animation and marketing",
    "Animation and social media"
  ],
  "Family & relationships": [
    "Marriage",
    "Divorce",
    "Childhood",
    "Adolescence",
    "Adulthood",
    "Parenting",
    "Siblings",
    "Extended family",
    "Blended families",
    "Single parenting",
    "Co-parenting",
    "Empty nest syndrome",
    "Intergenerational relationships",
    "Grandparenting",
    "Aging",
    "Elder care",
    "End-of-life issues",
    "Death and bereavement",
    "Grief and loss",
    "Mental health in the family",
    "Communication in relationships",
    "Conflict resolution in relationships",
    "Intimacy and sexuality in relationships",
    "Boundaries in relationships",
    "Trust in relationships",
    "Commitment in relationships",
    "Love and romance in relationships",
    "Friendship",
    "Social support",
    "Work-life balance",
    "Time management",
    "Stress management",
    "Self-care",
    "Self-esteem",
    "Confidence",
    "Resilience",
    "Coping with change",
    "Dealing with disappointment",
    "Setting goals",
    "Achieving success",
    "Personal growth",
    "Personal development",
    "Personal relationships",
    "Professional relationships",
    "Interpersonal skills",
    "Empathy",
    "Etiquette"
  ],
  "Science": [
    "Physics",
    "Chemistry",
    "Biology",
    "Astronomy",
    "Geology",
    "Meteorology",
    "Oceanography",
    "Environmental science",
    "Psychology",
    "Neuroscience",
    "Cognitive science",
    "Computer science",
    "Information technology",
    "Artificial intelligence",
    "Machine learning",
    "Data science",
    "Big data",
    "Statistics",
    "Mathematics",
    "Algorithms",
    "Logic",
    "Modeling",
    "Simulation",
    "Experimentation",
    "Observation",
    "Measurement",
    "Data analysis",
    "Data visualization",
    "Scientific method",
    "The scientific process",
    "The scientific community",
    "Scientific ethics",
    "Scientific skepticism",
    "Scientific literacy",
    "Science education",
    "Science communication",
    "Science and society",
    "Science and culture",
    "Science and religion",
    "Science and politics",
    "Science and the media",
    "Science and the environment",
    "Science and health",
    "Science and technology",
    "Science and business",
    "Science and economics",
    "Science and law",
    "Science and engineering",
    "Science and art",
    "Science and music",
    "Science and literature",
    "Science and philosophy"
  ],
  "Fitness": [
    "Weight loss",
    "Muscle building",
    "Endurance training",
    "Strength training",
    "Cardio",
    "HIIT",
    "Yoga",
    "Pilates",
    "Martial arts",
    "Dance",
    "Gymnastics",
    "Team sports",
    "Individual sports",
    "Outdoor sports and activities",
    "Adventure sports",
    "Aerobics",
    "Fitness classes",
    "Fitness competitions",
    "Fitness goals",
    "Fitness motivation",
    "Fitness routines",
    "Fitness planning",
    "Fitness tracking",
    "Fitness apps",
    "Fitness equipment",
    "Fitness nutrition",
    "Fitness supplements",
    "Fitness recovery",
    "Fitness injuries",
    "Fitness psychology",
    "Fitness and wellness",
    "Fitness and health",
    "Fitness and aging",
    "Fitness and lifestyle",
    "Fitness and culture",
    "Fitness and social issues",
    "Fitness and education",
    "Fitness and psychology",
    "Fitness and philosophy",
    "Fitness and politics",
    "Fitness and art",
    "Fitness and literature",
    "Fitness and music",
    "Fitness and film",
    "Fitness and television",
    "Fitness and gaming",
    "Fitness and advertising",
    "Fitness and branding",
    "Fitness and marketing",
    "Fitness and social media"
  ],
  "Careers": [
    "Job search",
    "Resume writing",
    "Cover letters",
    "Interviews",
    "Networking",
    "Professional development",
    "Career advancement",
    "Career change",
    "Entrepreneurship",
    "Freelancing",
    "Consulting",
    "Contract work",
    "Part-time work",
    "Full-time work",
    "Remote work",
    "Internships",
    "Apprenticeships",
    "Mentorship",
    "Leadership",
    "Management",
    "Team building",
    "Conflict resolution in the workplace",
    "Communication in the workplace",
    "Time management",
    "Stress management",
    "Work-life balance",
    "Diversity and inclusion in the workplace",
    "Equal opportunity in the workplace",
    "Workplace culture",
    "Workplace ethics",
    "Workplace laws and regulations",
    "Workplace safety",
    "Workplace benefits",
    "Workplace compensation",
    "Workplace negotiation",
    "Workplace conflict",
    "Workplace harassment",
    "Workplace discrimination",
    "Workplace politics",
    "Workplace networking",
    "Workplace mentorship",
    "Workplace teamwork",
    "Workplace leadership",
    "Workplace management",
    "Workplace productivity",
    "Workplace organization",
    "Workplace technology",
    "Workplace trends",
    "Workplace diversity",
    "Workplace culture",
    "Workplace communication",
    "Workplace ethics",
    "Workplace laws and regulations",
    "Workplace safety",
    "Workplace benefits",
    "Workplace compensation",
    "Workplace negotiation",
    "Workplace conflict",
    "Workplace harassment",
    "Workplace discrimination",
    "Workplace politics",
    "Workplace networking",
    "Workplace mentorship",
    "Workplace teamwork",
    "Workplace leadership",
    "Workplace management",
    "Career counseling",
    "Career coaching",
    "Career assessment",
    "Career planning",
    "Career development",
    "Career advancement",
    "Career change",
    "Career path",
    "Career trajectory",
    "Career growth",
    "Career success",
    "Career satisfaction",
    "Career fulfillment",
    "Career happiness",
    "Career legacy"
  ],
};
