// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6vCHrCIWWIJV31T1yhbWfjNJb5yBYpM',
    appId: '1:265206873848:web:50fd7b3cf635606900450d',
    messagingSenderId: '265206873848',
    projectId: 'spark-e3de0',
    authDomain: 'spark-e3de0.firebaseapp.com',
    storageBucket: 'spark-e3de0.appspot.com',
    measurementId: 'G-TF3SHZWSQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92Zlb0g0hdKQe0-uOsOxGGYLNPMmmYrE',
    appId: '1:265206873848:android:e309ba9d8f54272800450d',
    messagingSenderId: '265206873848',
    projectId: 'spark-e3de0',
    storageBucket: 'spark-e3de0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH1LeHFxve7VRKRZ4iQA7Bqjo4sf3sTys',
    appId: '1:265206873848:ios:4c49c7dd99297e1b00450d',
    messagingSenderId: '265206873848',
    projectId: 'spark-e3de0',
    storageBucket: 'spark-e3de0.appspot.com',
    iosClientId: '265206873848-5029s26h184fddt4i2hf1krhorvbem68.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH1LeHFxve7VRKRZ4iQA7Bqjo4sf3sTys',
    appId: '1:265206873848:ios:4c49c7dd99297e1b00450d',
    messagingSenderId: '265206873848',
    projectId: 'spark-e3de0',
    storageBucket: 'spark-e3de0.appspot.com',
    iosClientId: '265206873848-5029s26h184fddt4i2hf1krhorvbem68.apps.googleusercontent.com',
    iosBundleId: 'com.example.spark',
  );
}
